name: Deploy to FTP

on:
  push:
    branches:
      - section/location
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare index.html
        run: cp art-apartment-v13.html index.html
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 389998.w98.wedos.net
          username: w389998
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/
          exclude: |
            **/.git*
            **/.git*/**
            map-section.html
